### PR TITLE
Added position to ShowField

### PR DESCRIPTION
**Pull request by lukepass**
I am targeting this branch because it is a new feature.

Closes #{put_issue_number_here}

### Added
- Added position to show fields that allows specifying in which order they will be added

### CODE REVIEW

**Comment by kunicmarko20** [comment]
Hey @lukepass I really didn't have time or willpower to help around this, if you want I can give you collaboration rights and you can take over the bundle if you want?

**Comment by lukepass** [comment]
Hey @kunicmarko20 I surely will continue to use this bundle and add new features to it. We are using it in my company and I find it very useful, it saves a lot of time.
If you want I can help with it!

**Comment by kunicmarko20** [comment]
Awesome! I invited you to be a collaborator (https://github.com/kunicmarko20/SonataAnnotationBundle/invitations), you will have push rights and I leave the ownership to you.

**Comment by lukepass** [comment]
This is now obsolete.

**Pull request closed without merging**
