### PR TITLE
Show position

### PR DESCRIPTION
**Pull request by lukepass**
I am targeting this branch because it's the development branch.

Partially closes #{37}

## Changelog

```markdown
### Added

- Added position ShowField
- Added php-cs-fixer and its configuration

### Changed

- Updated doc

### CODE REVIEW

**Comment by lukepass** [comment]
@kunicmarko20 sorry, do you know why some checks don't pass? I added new tests and they are all passing in my local environment. Thanks!

**Comment by kunicmarko20** [comment]
https://travis-ci.org/kunicmarko20/SonataAnnotationBundle/jobs/554195193#L508 Composer running out of memory

**Comment by lukepass** [comment]
Is it something I am in control of? All the tests are passing fine in my environment. Thanks.

**Comment by kunicmarko20** [comment]
Maybe re running the tests, if you login to travis with your github account you should have permission around settings. Also all the config is in this repo https://github.com/kunicmarko20/SonataAnnotationBundle/tree/1.x/.travis

**Pull request merged**
